name: weather_appp
description: A Flutter weather app with BLoC, forecast, and theme support.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.4

  # HTTP Request
  http: ^1.1.0

  # Location
  geolocator: ^11.0.0

  # Date formatting
  intl: ^0.20.2

  # Animation
  lottie: ^3.3.1

  equatable: ^2.0.7

  # UI Utilities
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/sunny.json
    - assets/rain.json
    - assets/cloudy.json
